### ISSUE TITLE
NPE on tests and in single module projects.

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-slf4j-logger#2]
The current release provides a Java class (compiled code) that works as one of the implementations for the slf4j logger. It leads to NPE if this class is selected as a logging engine by slf4j (in tests for example). See https://github.com/foal/gwt-time/discussions/5#discussioncomment-380644 for example.

A possible solution is to remove the Java class and left only Java sources in the released jar.

**Comment by gkresic** [comment]
I stumbled upon at least one more situations where `domino-slf4j-logger-1.0.1.jar`'s implementation of `org.slf4j.LoggerFactory` gets into way: when running GWT CodeServer.

CodeServer is executed on "backend" (inside Jetty container), but it should have access to _both_ implementations of `LoggerFactory`: "regular" sjf4j's version for logging output from embedded Jetty and DominoKit's version for compiling GWT's client-side code. I "fixed" this by putting DominoKit's implementation if front of classpath and setting property `domino.slf4j.logging.level' to `OFF`. However, that kills both Jetty output on backend and DominoUI's output on client.

So, I believe that this bug should be reopened.

**Comment by vegegoku** [comment]
I believe this was fixed in 1.0.2 release, are you adding the directly or fetched as a transitive dependency?!

**Comment by gkresic** [comment]
My mistake, I'm sorry, didn't see that 1.0.1 was being pull in. 1.0.2 works fine.

**Comment by gkresic** [comment]
Just out of curiosity: is there a reason why `org.slf4j.LoggerFactory` isn't super-sourced for client-side usage? I never tried super-sourcing anything outside of java.* namespace, but I can't see a reason why it shouldn't work and it would be much cleaner that just excluding .class files from packaged jar.

One more reason to explore source-sourced approach: I'm not sure how this "hijacking" of `org.slf4j` package would work well in regard to JPMS: https://cr.openjdk.java.net/~mr/jigsaw/spec/jar.html#sealing

**Comment by vegegoku** [comment]
This topic sounds like a good discussion candidate.
The context for this isn't simple and the factor playing here are many, one we **j2cl/GWT3 vs GWT2**, **Lib vs App**, and finally **Mixed vs Separated classpath**

for the first one meanwhile, there is super sourcing for GWT2 we don't have super sourcing in j2cl (it is there for jre and some other stuff but no easy way to use it in libs and apps)

so the solution here would have 2 versions of domino-slf4j-logger, one with super sourcing for GWT2 and one without the super sourcing for j2cl... this means each library out there will also be forked with 2 versions if it wants to use domino-slf4j-logger and support both compilers.

Next Lib vs App: Should a library depend on logger implementation? probably not .. maybe libs should only depend on slf4j-api but not domino-slf4j-logger, Apps on the other hand should include the implementation (notice that the domino-slf4j-logger is implementation, not API) but this takes us back to the super source issue for slf4j-api, right?

finally Mixed vs Separated classpath: in J2CL we don't have this issue since separated classpath is forced. but in GWT2 we can mix class and in regards to super-sourcing or not we will still face issues but including two implementations in our app. and this was the original trigger for this issue, so it all boils here where the mixed classpath will end up making issues even if we apply any of the solutions I mentioned.

So as a result we applied the current solution as a workaround until we figure a proper way to address this issue with a mixed classpath.

**Comment by gkresic** [comment]
Oh, I didn't know that J2CL changed the way emulation works. From what I could find (docs are very sparse on this topic, though), it seems that they prefer swapping source paths for Java vs. J2CL builds:

https://github.com/google/j2cl/blob/master/docs/best-practices.md#super-sourcing-writing-platform-specific-code

If that's the preferred future-proof way, than it should be possible to have one implementation that could support both GWT2 and J2CL, but with extra work inside build tool to separate sources that should go to javac from the ones going to GWT/J2CL.

Library (like DominoUI) should definitely depend only on API, not implementation, but since `domino-slf4j-logger` is currently only SLF4J implementation for client side, there are no current benefits in separating the two.
